
/* Table to store products details */
CREATE TABLE dbo.PRODUCT_INFO
(
    PRODUCT_ID BIGINT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    PRODUCT_NAME NVARCHAR(50) NOT NULL,
    CATEGORY_ID INT NOT NULL,
    CREATED_BY BIGINT NOT NULL,
    CREATED_ON DATETIME NOT NULL
        FOREIGN KEY (CATEGORY_ID) REFERENCES dbo.PRODUCT_CATEGORY (CATEGORY_ID)
);

