
/* Table to store complete order details */
/* Contains the list of items ordered in a order along with the attributes info */
CREATE TABLE dbo.ORDER_ITEMS
(
    ITEM_ID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ATTRIBUTE_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    ORDER_DATE DATETIME NOT NULL,
    DELIVERED_DATE DATETIME NULL
        FOREIGN KEY (ORDER_ID) REFERENCES dbo.ORDER_INFO (ORDER_ID),
    FOREIGN KEY (PRODUCT_ATTRIBUTE_ID) REFERENCES dbo.PRODUCT_ATTRIBUTE_DETAILS (PRODUCT_ATTRIBUTE_ID)
);