
/* Table to store customer details */
CREATE TABLE dbo.CUSTOMER
(
    CUSTOMER_ID BIGINT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    FIRST_NAME NVARCHAR(50) NOT NULL,
    LAST_NAME NVARCHAR(50) NOT NULL,
    PHONE VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    STREET VARCHAR(255) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(25) NOT NULL,
    ZIP_CODE VARCHAR(6) NOT NULL,
    IS_ADMIN BIT NOT NULL
        DEFAULT (0),
    CREATED_ON DATETIME NOT NULL
);

