
/* Table to store order details, who ordered */
CREATE TABLE dbo.ORDER_INFO
(
    ORDER_ID BIGINT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    ORDER_STATUS INT NOT NULL,
    ORDER_DATE DATETIME NOT NULL
        FOREIGN KEY (CUSTOMER_ID) REFERENCES dbo.CUSTOMER (CUSTOMER_ID),
    FOREIGN KEY (ORDER_STATUS) REFERENCES dbo.ORDER_STATUS (STATUS_ID)
);

