CREATE PROCEDURE dbo.USP_ORDER_ITEMS_REPORT
    @PAGE_NO INT = 1,
    @PAGE_SIZE INT = 10
AS
BEGIN
    SET NOCOUNT ON;

    SELECT PRI.PRODUCT_NAME,
           PAD.PRICE,
           OI.QUANTITY,
           AI.ATTRIBUTE_NAME,
           PAD.ATTRIBUTE_VALUE,
           O.ORDER_DATE,
           OS.STATUS_DESCRIPTION AS ORDER_STATUS,
           COUNT(1) OVER () AS TOTAL_COUNT
    FROM dbo.ORDER_ITEMS OI
        INNER JOIN dbo.ORDER_INFO O
            ON O.ORDER_ID = OI.ORDER_ID
        INNER JOIN dbo.PRODUCT_ATTRIBUTE_DETAILS PAD
            ON PAD.PRODUCT_ATTRIBUTE_ID = OI.PRODUCT_ATTRIBUTE_ID
        INNER JOIN dbo.PRODUCT_INFO PRI
            ON PRI.PRODUCT_ID = PAD.PRODUCT_ID
        INNER JOIN dbo.ATTRIBUTE_INFO AI
            ON AI.ATTRIBUTE_ID = PAD.ATTRIBUTE_ID
        INNER JOIN dbo.ORDER_STATUS OS
            ON OS.STATUS_ID = O.ORDER_STATUS
    ORDER BY O.ORDER_ID OFFSET (@PAGE_NO * @PAGE_SIZE) - @PAGE_SIZE ROWS FETCH NEXT @PAGE_SIZE ROWS ONLY;
END;
GO

